[package]
name = "integration-tests"
version = "0.0.1"
edition = "2021"

[dependencies]
strava-wrapper = { path = "../strava-wrapper" }
#strava-wrapper-macros = { path = "../strava-wrapper-macros" }
tokio = "1.47.1"
httpmock = "0.8.0-alpha.1"
serde_json = "1.0.132"
