name: Publish Crate

on:
  workflow_dispatch:
    inputs:
      publish_macros:
        type: boolean
        description: "Also publish the macros crate?"
        required: false
        default: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Tests
        run: cargo test --all --verbose

      - name: Check Package
        run: cargo package --allow-dirty --no-verify

      - name: Publish strava-wrapper-macros
        if: ${{ inputs.publish_macros }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish -p strava-wrapper-macros

      - name: Publish strava-wrapper
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish -p strava-wrapper
